[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
contigo_voz = "EoHkqQVDX5rdYJVrZdCZVAY848TExEsbuWB8NLs7sQoV"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
